# Generated by Django 3.2.8 on 2021-10-29 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friends', '0001_initial'),
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='requests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='friends.friendrequest'),
        ),
    ]
