# Generated by Django 3.2.6 on 2021-10-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0003_auto_20211017_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.SmallIntegerField(choices=[(3, 'PRIVATE'), (1, 'PUBLIC'), (4, 'UNLISTED'), (2, 'FRIEND ONLY')], default=1),
        ),
    ]
