# Generated by Django 3.2.8 on 2021-10-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0003_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='select_user',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(4, 'UNLISTED'), (1, 'PUBLIC'), (2, 'FRIEND ONLY'), (3, 'PRIVATE')], default=1),
        ),
    ]
