# Generated by Django 3.1.6 on 2021-10-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0006_auto_20211019_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followauthor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.SmallIntegerField(choices=[(3, 'PRIVATE'), (2, 'FRIEND ONLY'), (1, 'PUBLIC'), (4, 'UNLISTED')], default=1),
        ),
        migrations.AlterField(
            model_name='registercontrol',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
