# Generated by Django 3.2.8 on 2021-10-28 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_auto_20211026_1002'),
        ('Author', '0007_auto_20211022_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(blank=True, max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to=settings.AUTH_USER_MODEL)),
                ('requests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='friends.friendrequest')),
            ],
        ),
        migrations.RemoveField(
            model_name='friend',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('published',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='published',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='contentType',
            field=models.CharField(default='default_type', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(1, 'PUBLIC'), (3, 'PRIVATE'), (2, 'FRIEND ONLY')], default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registercontrol',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.DeleteModel(
            name='FollowAuthor',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
