# Generated by Django 3.2.8 on 2021-10-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0008_auto_20211028_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='select_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(1, 'PUBLIC'), (4, 'UNLISTED'), (3, 'PRIVATE'), (2, 'FRIEND ONLY')], default=1),
        ),
    ]
