# Generated by Django 3.2.8 on 2021-10-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0009_alter_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='select_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.TextField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain'), ('application/base64', 'application/base64'), ('image/png;base64', 'image/png;base64'), ('image/jpeg;base64', 'image/jpeg;base64')], default='text/plain'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(4, 'UNLISTED'), (2, 'FRIEND ONLY'), (1, 'PUBLIC'), (3, 'PRIVATE')], default=1),
        ),
    ]
