# Generated by Django 3.2.8 on 2021-10-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0010_auto_20211029_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(1, 'PUBLIC'), (2, 'FRIEND ONLY'), (4, 'UNLISTED'), (3, 'PRIVATE')], default=1),
        ),
    ]
