# Generated by Django 3.1.6 on 2021-10-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0011_auto_20211022_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.SmallIntegerField(choices=[(2, 'FRIEND ONLY'), (3, 'PRIVATE'), (4, 'UNLISTED'), (1, 'PUBLIC')], default=1),
        ),
    ]
