# Generated by Django 3.2.8 on 2021-10-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0012_auto_20211029_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(2, 'FRIEND ONLY'), (4, 'UNLISTED'), (3, 'PRIVATE'), (1, 'PUBLIC')], default=1),
        ),
    ]
