# Generated by Django 3.2.8 on 2021-11-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='api_url',
            field=models.URLField(default='', editable=False),
        ),
    ]
