# Generated by Django 3.1.6 on 2021-10-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_auto_20211029_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='respond_status',
        ),
    ]
