# Generated by Django 3.1.6 on 2021-10-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_remove_friendrequest_respond_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='respond_status',
            field=models.BooleanField(default=False),
        ),
    ]
