# Generated by Django 3.2.8 on 2021-11-23 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_auto_20211029_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver',
            field=models.JSONField(default=dict, max_length=2000),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='sender',
            field=models.JSONField(default=dict, max_length=2000),
        ),
    ]
