# Generated by Django 3.2.8 on 2021-12-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_file',
        ),
    ]
