# Generated by Django 3.2.8 on 2021-11-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(4, 'UNLISTED'), (2, 'FRIEND ONLY'), (3, 'PRIVATE'), (1, 'PUBLIC')], default=1),
        ),
    ]
