# Generated by Django 3.2.8 on 2021-12-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_remove_post_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.TextField(),
        ),
    ]
