# Generated by Django 3.2.8 on 2021-10-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_inbox_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(3, 'PRIVATE'), (2, 'FRIEND ONLY'), (4, 'UNLISTED'), (1, 'PUBLIC')], default=1),
        ),
    ]
