# Generated by Django 3.2.8 on 2021-11-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0003_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(4, 'UNLISTED'), (3, 'PRIVATE'), (1, 'PUBLIC'), (2, 'FRIEND ONLY')], default=1),
        ),
    ]
