# Generated by Django 3.2.8 on 2021-11-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0004_auto_20211029_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('host', models.URLField(default='', primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(1, 'PUBLIC'), (3, 'PRIVATE'), (4, 'UNLISTED'), (2, 'FRIEND ONLY')], default=1),
        ),
    ]
