# Generated by Django 3.2.8 on 2021-11-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0008_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(2, 'FRIEND ONLY'), (3, 'PRIVATE'), (4, 'UNLISTED'), (1, 'PUBLIC')], default=1),
        ),
    ]
