# Generated by Django 3.2.8 on 2021-11-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0009_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(3, 'PRIVATE'), (4, 'UNLISTED'), (1, 'PUBLIC'), (2, 'FRIEND ONLY')], default=1),
        ),
    ]
