# Generated by Django 3.2.8 on 2021-11-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0009_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(2, 'FRIEND ONLY'), (1, 'PUBLIC'), (4, 'UNLISTED'), (3, 'PRIVATE')], default=1),
        ),
    ]
