# Generated by Django 3.2.8 on 2021-11-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0010_alter_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_url',
            field=models.URLField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.URLField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.URLField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(4, 'UNLISTED'), (1, 'PUBLIC'), (2, 'FRIEND ONLY'), (3, 'PRIVATE')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
