# Generated by Django 3.2.8 on 2021-11-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0014_alter_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='api_url',
            field=models.URLField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(1, 'PUBLIC'), (2, 'FRIEND ONLY'), (4, 'UNLISTED'), (3, 'PRIVATE')], default=1),
        ),
    ]
