# Generated by Django 3.2.8 on 2021-11-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0015_auto_20211122_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(3, 'PRIVATE'), (1, 'PUBLIC'), (4, 'UNLISTED'), (2, 'FRIEND ONLY')], default=1),
        ),
    ]
