# Generated by Django 3.2.8 on 2021-11-23 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0017_alter_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='allow_connection',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(3, 'PRIVATE'), (2, 'FRIEND ONLY'), (1, 'PUBLIC'), (4, 'UNLISTED')], default=1),
        ),
    ]
