# Generated by Django 3.2.8 on 2021-11-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0018_auto_20211123_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='created',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='requests',
        ),
        migrations.AlterField(
            model_name='inbox',
            name='items',
            field=models.JSONField(default=list, max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.SmallIntegerField(choices=[(1, 'PUBLIC'), (2, 'FRIEND ONLY'), (3, 'PRIVATE'), (4, 'UNLISTED')], default=1),
        ),
    ]
