# Generated by Django 3.1.6 on 2021-10-22 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20211022_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='request_id',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
