# Generated by Django 3.1.6 on 2021-10-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_auto_20211022_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='request_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
