# Generated by Django 3.1.6 on 2021-10-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_auto_20211022_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='request_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
