# Generated by Django 3.2.8 on 2021-10-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_auto_20211026_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='respond_status',
            field=models.BooleanField(default=False),
        ),
    ]
