# Generated by Django 3.1.6 on 2021-10-22 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0007_auto_20211022_0543'),
    ]

    operations = [
    ]
