# Generated by Django 3.1.6 on 2021-10-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0008_auto_20211022_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='requestid',
            new_name='request_id',
        ),
    ]
