# Generated by Django 3.1.6 on 2021-10-22 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0009_auto_20211022_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='request_id',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
