# Generated by Django 3.1.6 on 2021-10-22 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0010_auto_20211022_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
